name: Publish to Modrinth & CurseForge

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java 25
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # Fix permissions automatically
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Artifacts
        run: ./gradlew build

      - name: Publish to Modrinth and CurseForge
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          # Inputs
          modrinth-id: mixed-stacks
          curseforge-id: mixed-stacks
          
          # Secrets
          modrinth-token: ${{ secrets.MODRINTH_API_KEY }}
          curseforge-token: ${{ secrets.CURSEFORGE_API_KEY }}

          # File selection
          files: |
            build/libs/!(*-dev|*-sources).jar

          # Metadata
          name: ${{ github.event.release.name }}
          version: ${{ github.event.release.tag_name }}
          version-type: beta
          changelog: ${{ github.event.release.body }}
          
# Compatibility
          loaders: |
            fabric
          game-versions: |
            1.21
            1.21.1
